#ifndef ROSS_H
#define ROSS_H

// name: tr|Q949S7|Q949S7_ARATH
// desc: NAD(P)-binding Rossmann-fold superfamily protein OS=Arabidopsis
// thaliana OX=3702 GN=At5g15910 PE=1 SV=1

static char const ross[] = {
    "MLRSLIWKRSQAYSSVVTMSSISQRGNERLLSEVAGSHSRDNKILVLGGNGYVGSHICKE"
    "ALRQGFSVSSLSRSGRSSLHDSWVDDVTWHQGDLLSPDSLKPALEGITSVISCVGGFGSN"
    "SQMVRINGTANINAVKAAAEQGVKRFVYISAADFGVINNLIRGYFEGKRATEAEILDKFG"
    "NRGSVLRPGFIHGTRQVGSIKLPLSLIGAPLEMVLKLLPKEVTKIPVIGPLLIPPVNVKS"
    "VAATAVKAAVDPEFASGVIDVYRILQHGH"};

#endif
